# .streamlit/secrets.toml

[connections.mysql]
dialect = "mysql"
host = "eiz-test01.ccub4ta9krao.ap-southeast-2.rds.amazonaws.com"
port = 3306
database = "eiz_test"
username = "eiz"
password = "Adgjl!2345"