# .streamlit/secrets.toml

[connections.eiz_test]
dialect = "mysql"
host = "master.ccub4ta9krao.ap-southeast-2.rds.amazonaws.com"
port = 3306
database = "eiz_test"
username = "viewuser"
password = ")5y)JHhqsFulugU!"